/*
by coolhezker

The Concepts namespace defines several C++20 concepts, which are used to constrain template types. These concepts are used to ensure that the types passed to templates meet certain criteria.

OStream: Checks if a type supports the << operator for output streaming.
IStream: Checks if a type supports the >> operator for input streaming.
Streams: Combines OStream and IStream, ensuring that a type supports both input and output streaming.
CConstruct: Checks if a type has a copy constructor.
CAssign: Checks if a type supports copy assignment.
CopyCA: Combines CConstruct and CAssign, ensuring the type supports both copy construction and assignment.
General: Combines Streams and CopyCA, ensuring that a type supports streaming and copy operations.
The Task class is constrained using the General concept, which ensures that the content type of the task supports input/output streaming and copy operations.

text generated by ChatGPT(not Code)
*/

#ifndef CONCEPTS_H
#define CONCEPTS_H

#include <iostream>

namespace Concepts {
	template<typename T>
	concept OStream = requires(T t, std::ostream & os) { // check operator<<
		os << t;
	};

	template<typename T>
	concept IStream = requires(T t, std::istream & is) { // check operator>>
		is >> t;
	};

	template<typename T>
	concept Streams = IStream<T> && OStream<T>; // combine IStream concept and OStream concept

	template<typename T>
	concept CConstruct = requires(T t) { // check Copy Constructor
		T(t);
	};

	template<typename T> // check Copy Assign
	concept CAssign = requires(T t1, T t2) {
		t1 = t2;
	};

	template<typename T> // combine CAssign concept and CConstruct concept
	concept CopyCA = CAssign<T> && CConstruct<T>;

	template<typename T> // combine CopyCA concept and Streams concept. (combine all concepts)
	concept General = Streams<T> && CopyCA<T>;
}

#endif // !CONCEPTS_H
